version: '3.8'

services:

app: image: autonomous_threat_hunter:latest container_name: autonomous_threat_hunter restart: always ports:

"8000:8000" depends_on:
redis
db environment:
REDIS_HOST=redis
REDIS_PORT=6379
DATABASE_URL=postgres://user:password@db:5432/dbname
redis: image: redis:latest container_name: autonomous_threat_hunter_redis restart: always volumes:

redis_data:/data
db: image: postgres:latest container_name: autonomous_threat_hunter_db restart: always volumes:

postgres_data:/var/lib/postgresql/data environment:
POSTGRES_USER=user
POSTGRES_PASSWORD=password
POSTGRES_DB=dbname
nginx: image: nginx:latest container_name: autonomous_threat_hunter_nginx restart: always ports:

"80:80" volumes:
./nginx/default.conf:/etc/nginx/conf.d/default.conf
./app/static:/app/static depends_on:
app
volumes:

redis_data: postgres_data:

This docker-compose.yml file defines four services: app, redis, db, and nginx. The app service uses the autonomous_threat_hunter Docker image and depends on the redis and db services. The redis and db services use the official redis and postgres images, respectively. The nginx service uses the official nginx image and proxies requests to the app service.

The app service exposes port 8000, and nginx exposes port 80. The redis and db services store their data in named volumes.

The app service uses environment variables to configure the Redis and Postgres connections. The db service uses environment variables to configure the Postgres database.

The nginx service uses a custom configuration file (./nginx/default.conf) and mounts the ./app/static directory as a volume to serve static files.

Note: Replace user, password, and dbname with your own values. Also, make sure to create the ./nginx/default.conf file with the appropriate configuration for your application.
